#!/usr/bin/env python3
"""Guard against documentation drift for azure-functions-doctor.

This script asserts two invariants so CI fails fast when docs fall behind the
shipped package:

1. **Version parity** — the canonical ``__version__`` declared in
   ``src/azure_functions_doctor/__init__.py`` must match every canonical version
   statement in the AI-assistant/docs surface (``llms.txt``, ``llms-full.txt``
   and ``docs/deployment.md``).
2. **Rule-inventory parity** — the set of rule IDs shipped in
   ``assets/rules/v2.json`` must exactly match the rule IDs documented in
   ``docs/rule_inventory.md`` (which is regenerated by
   ``scripts/gen_rule_inventory.py``).

Usage:
    python scripts/check_docs_consistency.py   # exit 1 on any drift
"""

from __future__ import annotations

import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parent.parent
INIT_PY = ROOT / "src" / "azure_functions_doctor" / "__init__.py"
RULES_JSON = ROOT / "src" / "azure_functions_doctor" / "assets" / "rules" / "v2.json"
INVENTORY_MD = ROOT / "docs" / "rule_inventory.md"


def _read_version() -> str:
    text = INIT_PY.read_text(encoding="utf-8")
    match = re.search(r'^__version__\s*=\s*["\']([^"\']+)["\']', text, re.MULTILINE)
    if not match:
        raise SystemExit(f"Could not find __version__ in {INIT_PY}")
    return match.group(1)


def _check_version_refs(version: str) -> list[str]:
    """Return a list of human-readable error strings (empty when consistent)."""
    errors: list[str] = []
    canonical_refs = {
        "llms.txt": f"- Version: {version}",
        "llms-full.txt": f"- Version: {version}",
        "docs/deployment.md": f"Doctor CLI v{version}",
        "README.md": f"package version ({version})",
    }
    for rel_path, needle in canonical_refs.items():
        path = ROOT / rel_path
        content = path.read_text(encoding="utf-8")
        if needle not in content:
            errors.append(
                f"{rel_path}: expected canonical version string {needle!r} "
                f"(does __version__={version} match this file?)"
            )
    return errors


def _rule_ids_from_json() -> set[str]:
    rules = json.loads(RULES_JSON.read_text(encoding="utf-8"))
    return {rule["id"] for rule in rules}


def _rule_ids_from_inventory() -> set[str]:
    content = INVENTORY_MD.read_text(encoding="utf-8")
    # Only inspect the generated "## Rule Table" block; later hand-authored
    # sections (e.g. "## Rule Types") also contain backticked cells.
    if "## Rule Table" not in content or "## Rule Types" not in content:
        raise SystemExit(
            "docs/rule_inventory.md is missing the '## Rule Table' and/or "
            "'## Rule Types' headings; cannot verify rule-ID parity."
        )
    start = content.index("## Rule Table")
    end = content.index("## Rule Types")
    table = content[start:end]
    return set(re.findall(r"^\|\s*`([^`]+)`\s*\|", table, re.MULTILINE))


def _check_rule_inventory() -> list[str]:
    errors: list[str] = []
    json_ids = _rule_ids_from_json()
    doc_ids = _rule_ids_from_inventory()
    missing = json_ids - doc_ids
    extra = doc_ids - json_ids
    if missing:
        errors.append(
            "docs/rule_inventory.md is missing rule IDs present in v2.json: "
            + ", ".join(sorted(missing))
        )
    if extra:
        errors.append(
            "docs/rule_inventory.md lists rule IDs absent from v2.json: " + ", ".join(sorted(extra))
        )
    if errors:
        errors.append("Fix with: python scripts/gen_rule_inventory.py")
    return errors


def _check_readme_rule_count() -> list[str]:
    """Assert README's "N diagnostic checks" count matches the shipped ruleset."""
    readme = ROOT / "README.md"
    content = readme.read_text(encoding="utf-8")
    match = re.search(r"\*\*(\d+) diagnostic checks\*\*", content)
    if not match:
        return [
            "README.md: could not find a '**N diagnostic checks**' count to "
            "verify against the rule inventory."
        ]
    documented = int(match.group(1))
    actual = len(_rule_ids_from_json())
    if documented != actual:
        return [
            f"README.md: documented '{documented} diagnostic checks' does not "
            f"match the {actual} rules in v2.json. Update the count in README.md."
        ]
    return []


# Historical/hand-maintained docs that legitimately cite old counts.
_DOC_COUNT_EXEMPT = {
    "changelog.md",  # per-release history (counts at the time of writing)
}


def _check_doc_rule_counts() -> list[str]:
    """Assert every "N rules" count in docs/ matches the shipped ruleset.

    Catches the drift class where README's count is verified but sibling docs
    (semver policy, profile comparisons) silently keep an old total (issue:
    three stale "29 rules" mentions survived a verified guard because the
    guard only looked at README).
    """
    actual = len(_rule_ids_from_json())
    errors: list[str] = []
    patterns = (
        # "All 41 current built-in rules" / "All 41 rules in `v2.json`"
        re.compile(r"All (\d+) (?:current built-in )?rules"),
        # Comparison tables: "| Built-in count | 41 rules | 6 rules |"
        re.compile(r"\|\s*Built-in count\s*\|\s*(\d+) rules\s*\|"),
    )
    for doc in sorted((ROOT / "docs").glob("*.md")):
        if doc.name in _DOC_COUNT_EXEMPT:
            continue
        content = doc.read_text(encoding="utf-8")
        for pattern in patterns:
            for match in pattern.finditer(content):
                documented = int(match.group(1))
                if documented != actual:
                    errors.append(
                        f"docs/{doc.name}: rule count '{documented}' "
                        f'(near "{match.group(0)}") does not match the '
                        f"{actual} rules in v2.json."
                    )
    return errors


def main() -> int:
    version = _read_version()
    errors = (
        _check_version_refs(version)
        + _check_rule_inventory()
        + _check_readme_rule_count()
        + _check_doc_rule_counts()
    )
    if errors:
        print("Documentation consistency check FAILED:")
        for err in errors:
            print(f"  - {err}")
        return 1
    print(
        f"Documentation consistency check passed "
        f"(version {version}, {len(_rule_ids_from_json())} rules)."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
