#!/usr/bin/env python3
"""Regenerate the Rule Table in ``docs/rule_inventory.md`` from ``v2.json``.

The authoritative ruleset lives in
``src/azure_functions_doctor/assets/rules/v2.json``. This script regenerates the
``## Rule Table`` section (and its "last generated" stamp) so the inventory
never drifts from the shipped rules. Hand-authored sections such as
``## Rule Types`` and ``## False-positive Risk`` are preserved untouched.

Usage:
    python scripts/gen_rule_inventory.py          # rewrite the file in place
    python scripts/gen_rule_inventory.py --check   # exit 1 if it would change
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

# Ensure the in-repo package is importable when this script is run directly
# (e.g. ``python scripts/gen_rule_inventory.py`` in CI, without an editable install).
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from azure_functions_doctor.profiles import profiles_for_rule  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
RULES_JSON = ROOT / "src" / "azure_functions_doctor" / "assets" / "rules" / "v2.json"
INVENTORY_MD = ROOT / "docs" / "rule_inventory.md"

TABLE_HEADER = "## Rule Table"
NEXT_SECTION = "## Rule Types"
STAMP_PREFIX = "<!-- generated by scripts/gen_rule_inventory.py"


def _profile(rule: dict) -> str:
    # Profiles a rule participates in, derived from the single source of truth in
    # azure_functions_doctor.profiles.profiles_for_rule (matches runtime filtering).
    return ", ".join(profiles_for_rule(rule))


def _group(rule: dict) -> str:
    # Functional group of the rule. 'core' targets Azure runtime/hosting/deploy
    # correctness; 'integration' targets a specific ecosystem library and is only
    # meaningful when that library is present. Defaults to 'core' when omitted.
    return rule.get("group", "core")


def _render_table(rules: list[dict]) -> str:
    lines = [
        TABLE_HEADER,
        "",
        f"{STAMP_PREFIX} — do not edit this table by hand -->",
        "",
        "| Rule ID | Label | Category | Group | Section | Type | Required | Profile |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for rule in rules:
        required = "Yes" if rule.get("required", True) else "No"
        lines.append(
            f"| `{rule['id']}` | {rule.get('label', '')} | {rule.get('category', '')} "
            f"| {_group(rule)} | {rule.get('section', '')} | `{rule.get('type', '')}` | {required} "
            f"| {_profile(rule)} |"
        )
    lines.append("")
    return "\n".join(lines)


def _build(rules: list[dict], current: str) -> str:
    if TABLE_HEADER not in current or NEXT_SECTION not in current:
        raise SystemExit(
            f"docs/rule_inventory.md is missing required heading(s) "
            f"{TABLE_HEADER!r} and/or {NEXT_SECTION!r}; cannot regenerate the Rule Table."
        )
    start = current.index(TABLE_HEADER)
    end = current.index(NEXT_SECTION)
    return current[:start] + _render_table(rules) + "\n" + current[end:]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="fail if regeneration would change the file"
    )
    args = parser.parse_args()

    rules = json.loads(RULES_JSON.read_text(encoding="utf-8"))
    # Match Doctor._load_v2_rules execution order so the table stays stable
    # regardless of ordering in v2.json.
    rules = sorted(rules, key=lambda r: r.get("check_order", 999))
    current = INVENTORY_MD.read_text(encoding="utf-8")
    updated = _build(rules, current)

    if args.check:
        if updated != current:
            print(
                "docs/rule_inventory.md is out of date. Run: python scripts/gen_rule_inventory.py"
            )
            return 1
        print("docs/rule_inventory.md is up to date.")
        return 0

    if updated != current:
        INVENTORY_MD.write_text(updated, encoding="utf-8")
        print(f"Regenerated docs/rule_inventory.md ({len(rules)} rules).")
    else:
        print("docs/rule_inventory.md already up to date.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
